### ISSUE TITLE
Button should be disabled and in loading state after performing checkout action

### ISSUE THREAD

**Issue by kprzerwa** [inveniosoftware/react-invenio-app-ils#105]
Where: Backoffice item details page
<img width="1075" alt="Screenshot 2020-07-14 at 15 04 52" src="https://user-images.githubusercontent.com/38131488/87429029-7fc3ae00-c5e3-11ea-92fb-5e2658af4cd8.png">

What should happen:
Before choosing the patron the checkout button should be disabled.
After choosing the patron the checkout button should be enabled.
After clicking "Checkout physical copy" all the visible checkout buttons should be in disabled and loading state until the action finishes with the response. If there is no error, the checkout button should be blocked with the information that the item is already on loan an it cannot be checked out.

**Comment by FlorianCassayre** [comment]
Addressed by #118 
What's left to do: the button should be disabled when no patron is selected
