### ISSUE TITLE
remove Restricted facet from the patron search page

### ISSUE THREAD

**Issue by kprzerwa** [inveniosoftware/react-invenio-app-ils#108]
The facet `Restricted` should never appear in the patrons search.

This might be a result of a  bigger problem of wrongly assigned model types in `SearchControls` components. Review them **carefully**.

If not a problem with configuration, implement a solution to hide the filter when the user has no librarian or admin role or (good enough if the first case not possible) or leave the filter only for the backoffice search.

**Comment by FlorianCassayre** [comment]
It should also be noted that the `Restricted` checkboxes are not shown as checked when the user clicks them, regardless if they are a patron or a privileged user.
