### ISSUE TITLE
Loan request: Add different states to loan request page

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/react-invenio-app-ils#116]
When requesting a loan for a document, the user should see different states depending on the circumstances. Currently there are 2 states:

1. User is not logged in, (s)he has to sign in to be able to request a loan.
2. User is logged in and has no requests on the document, (s)he should be able to request a loan.

The goal is to add 2 new states:

3. User is logged in and already has a request for that document, (s)he should have a link to redirect him to the `Your loans` page and not have the request button available.
4. User is logged in and has a current loan active on the document, (s)he should be able to apply for an extension.

Potential enhancements:

- If the user already requested a loan of the document in the past, display `You requested a loan of this book 1 year ago`

### Tasks

- [x] Modify the component to display different states depending on the circumstances.
- [x] Display message if user requested a loan in the past.

Backend task: https://github.com/inveniosoftware/invenio-app-ils/issues/482

**Comment by FlorianCassayre** [comment]
A sketch of the different states (correct me if anything is wrong):

![image](https://user-images.githubusercontent.com/9027075/88290160-9ca06580-ccf6-11ea-8ef9-5f1ef17c2b03.png)

We shall also include all the relevant informations in the two new states (dates, etc.).

**Comment by FlorianCassayre** [comment]
https://github.com/FlorianCassayre/react-invenio-app-ils/tree/loan-request
