### ISSUE TITLE
Series details mobile view - display bug

### ISSUE THREAD

**Issue by kprzerwa** [inveniosoftware/react-invenio-app-ils#124]
<img width="1356" alt="Screenshot 2020-07-22 at 11 08 10" src="https://user-images.githubusercontent.com/38131488/88157908-a7320080-cc0b-11ea-8cb1-26a9f34e9154.png">
<img width="1033" alt="Screenshot 2020-07-22 at 11 08 24" src="https://user-images.githubusercontent.com/38131488/88157956-b5801c80-cc0b-11ea-942e-cc3b5a76e2fb.png">

**Comment by FlorianCassayre** [comment]
This usage is missing two required properties:
https://github.com/inveniosoftware/react-invenio-app-ils/blob/62d44c4140ced40a8e78dac34410a4398ae42b14/src/lib/pages/frontsite/Series/SeriesDetails/SeriesPanel/SeriesPanel.js#L84
