### ISSUE TITLE
ui: react [-router] caches urls response

### ISSUE THREAD

**Issue by equadon** [inveniosoftware/react-invenio-app-ils#13]
Steps to reproduce:
* Go to a loan details, for example `https://127.0.0.1:5000/backoffice/loans/18`
* You see the loan details page
* Perform an invalid action, you should the error 400 Invalid action
* Go back to loans list
* Click again on the **same** loan, `/loans/18`, same URL
* You see again 400 Invalid action

If you refresh the page, you see the loan details.

It looks like React/React-router is caching a previous state re-rendering the component in the previous state. Relevant issues:
* https://github.com/ReactTraining/react-router/issues/793
* https://github.com/ReactTraining/react-router/issues/800

**Comment by ntarocco** [comment]
It might have been also fixed when we remove the ETag and fixed the cache... to be re-tested

**Comment by KonstantinaStoikou** [comment]
Closing this because it is fixed.
