### ISSUE TITLE
Loan: Replace button not working properly

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/react-invenio-app-ils#144]
### Description
When replacing an item on loan with another physical copy, the page displays an error `TypeError: authors is undefined`. And after refreshing the replace was not correctly done, since the copy that was replaced is not displayed as an available copy anymore

**Comment by FlorianCassayre** [comment]
It seems that the artificial timeout on refresh is too low (or nonexistent?), because the button can be clicked several times before eventually disappearing.
