### ISSUE TITLE
PriceField component - Fix validation

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/react-invenio-app-ils#155]
The `PriceField` component is not validating properly the data, and not cleaning the data when submitting an empty value, this can causes a bug and it doesn't display any information. This component is not setting default values correctly, in some places there should be a default currency assigned but it is not. This bug doesn't allow to submit the form. Example in `purchase order` form.
![image](https://user-images.githubusercontent.com/15194802/89875602-c219e400-dbbd-11ea-8836-e02ac859b185.png)

the bug is blocking feature:
 Create new order: it is not working if we add payment information due to `price.currency` is not set   inveniosoftware/react-invenio-app-ils#155 if we don't supply the price though `<OrderStatistics>` component   throws `Uncaught TypeError: Cannot read property 'currency' of undefined` in details

**Comment by kprzerwa** [comment]
some more information:
the loader schema of the PriceField has both fields required, and the parent field is not. Is it correct?

validation is not matching with the correct field path within the form -> so when we have `order_line.0.unit_price.value` the field is not marked as errored

**Comment by kprzerwa** [comment]
https://github.com/inveniosoftware/react-invenio-app-ils/pull/162#issuecomment-674042363

**Comment by jrcastro2** [comment]
Currently the `PriceField` component is still not behaving properly, we should solve these problems:

- There are `PriceField` components that have the currency disabled, in this case if you enter the value and submit it will fail and in the response we can check the complain about the currency field. (This also happens with the `PriceField` components that have the currency enabled, we are forced to select a currency in this case). Even if it fails it's not showing any error message. 

  - [ ] Add error message
  - [ ] Set a default value, so we don't are forced to select a value.
- There are `PriceField` components that are required in the backend but not marked like that in the frontend, for instance, the `Order Line Unit Price` field in the `Purchase Orders`
  - [ ] Mark with the asterisk the required `PriceField` components 
- In the `acquisition order` form if we have an order with `Status != Cancelled` and we dont enter a value for the `Total` field it will crash when rendering the order details page. Solution: Check if `order.grand_total` is undefined before displaying it value or mark the field as required (if this makes sense)
  - [ ] Implement one of the above solutions (or another one) 
    <Details>

     ![image](https://user-images.githubusercontent.com/15194802/95225014-9ef56480-07fb-11eb-9660-64ed11159957.png)

    </Details>

**Comment by FlorianCassayre** [comment]
The `PriceField` is made out of two inputs, a dropdown (`currency`) and a number input (`value`). The `PriceField` can be _required_ or _optional_.
What should happen:
- the `currency` dropdown does not allow an empty selection, even if the whole `PriceField` is _optional_
- if the user leaves the number input empty then nothing should be submitted (= `price: undefined`)
- otherwise the whole price object is sent to the server `{ currency, value }`
- the inputs are only controled by the user (no visual side effects if the user clear the value input for instance)

**Comment by ntarocco** [comment]
Other bugs spotted:
1. on small screens (e.g. laptop), the dropdown component takes too much space, see screenshot
![price_field_error](https://user-images.githubusercontent.com/2089455/95860965-1168c600-0d61-11eb-83ff-767c244334a1.png)

2. when adding a new order line in the form, the `X` button to remove the order line is not working, nothing happens. Please check all forms that have such subforms.

**Comment by FlorianCassayre** [comment]
At least another component has a similar issue: the `isbn` accordion from documents. If the user touches the input but eventually leaves it empty (and collapses the accordion), the form will refuse to submit because now `isbn === {}` instead of `isbn === undefined`.
