### ISSUE TITLE
Clicking on tags on backoffice redirected to frontsite

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/react-invenio-app-ils#18]
Multiple issues here

## Frontsite/Backoffice search
* in the list view, tags should not be clickable, read-only, given that you can select tags from the left facets
* in the list view, tags are not displayed for series: add them
* check if tags are displayed in the backoffice series

## Frontsite/Backoffice details
* tags should not be clickable, read-only.

**Comment by kprzerwa** [comment]
this is also not working when:
1. clicking from the frontsite it leads to the backoffice

**Comment by FlorianCassayre** [comment]
Please take notice of the third bullet in #196: in the backoffice document search, clicking on a tag updates the url but does not reload the search results
