### ISSUE TITLE
Backoffice: fixed width on some fields in small screens

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/react-invenio-app-ils#186]
Package version (if known): <version>

## Describe the bug
The `datePicker` component has a fixed minimum width, and gets off the screen in smaller screens, `priceField` component seems to have also a fixed width in the currency selector.

## Steps to Reproduce
1. Open `DevToools`, click `Toggle device toolbar`(Ctrl + Shift + M) and select `Laptop with MDPI screen`
2. Go to `Purchase orders`
3. Click `create order`.
------------
1. Open `DevToools`, click `Toggle device toolbar`(Ctrl + Shift + M) and select `Laptop with MDPI screen`
2. Go to `Patrons`
3. Click on the first patron.

## Expected behavior
Both components (`datePicker` and `priceField`) should not have a fixed width.

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/15194802/92444122-bb798f00-f1b2-11ea-9ee4-3c6c676b03fa.png)
---------------
![image](https://user-images.githubusercontent.com/15194802/92882020-d3018380-f40f-11ea-86bf-463d6d98bef0.png)

**Comment by ntarocco** [comment]
The part with the document titles should be already fixed.
For the forms, acquisition is done (moved to RJSF), borrowing request to do.
