### ISSUE TITLE
Search fails over 10000k results

### ISSUE THREAD

**Issue by kprzerwa** [inveniosoftware/react-invenio-app-ils#207]
## Describe the bug
when navigating in the search to page 700 (15 results per page = 10500) the search interface crashes:

<img width="1530" alt="Screenshot 2020-09-29 at 08 58 53" src="https://user-images.githubusercontent.com/38131488/94523866-1e020000-0232-11eb-8467-059b84636527.png">
<img width="718" alt="Screenshot 2020-09-29 at 08 59 05" src="https://user-images.githubusercontent.com/38131488/94523871-1fcbc380-0232-11eb-8a8f-fbece19c46b6.png">
<img width="612" alt="Screenshot 2020-09-29 at 08 59 18" src="https://user-images.githubusercontent.com/38131488/94523875-20645a00-0232-11eb-89d3-f543004387e3.png">

see also: https://github.com/inveniosoftware/react-invenio-app-ils/issues/189

**Comment by FlorianCassayre** [comment]
To reproduce, change [this config field](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/config.py#L45) to a lower value (thanks Nicola for pointing it out!); ie. `21` which will fail for the second page.

**Comment by FlorianCassayre** [comment]
[Patches](https://gist.github.com/FlorianCassayre/4eea7fcd3720d9919f9b64f863826b73) (to be included with the other pagination PR)
