### ISSUE TITLE
frontsite: Patron cancel loan bug

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/react-invenio-app-ils#225]
Package version (if known): <version>

## Describe the bug
In the frontsite in the `your loans` section if we cancel a loan and we change pages, for example we go to the home page by clicking the ILS logo we will get an error 
## Steps to Reproduce
1. Go to `your loans`
2. Click on `cancel` for a loan
3. Click on ILS logo

## Expected behavior
Even if the action is not finished we should not get an error

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/15194802/95226422-34452880-07fd-11eb-9f57-255f238e5bbc.png)

## Additional context
Related issues: #30

**Comment by FlorianCassayre** [comment]
Nice catch!
In fact the use of `withCancel` was correct but they did not check if the component was unmounted at that point. There may be other occurrences of this issue; in a previous PR I went over all the editors, those should be correct at least.
