### ISSUE TITLE
backoffice: search UI crashes on mobile

### ISSUE THREAD

**Issue by FlorianCassayre** [inveniosoftware/react-invenio-app-ils#229]
For example: [https://dev-cds-ils.web.cern.ch/backoffice/series?q=](https://dev-cds-ils.web.cern.ch/backoffice/series?q=)

![image](https://user-images.githubusercontent.com/9027075/95468909-451da780-097f-11eb-9351-49e105380b4f.png)

**Comment by topless** [comment]
This one is fixed by #233

**Comment by FlorianCassayre** [comment]
Also fixed in #214, which is now part of `master`. Thanks for pinging
