### ISSUE TITLE
frontsite: broken loan request module

### ISSUE THREAD

**Issue by FlorianCassayre** [inveniosoftware/react-invenio-app-ils#241]
* go to a document details page on the frontsite
* request the document, the form should disappear and a confirmation message should be displayed
* now refresh the page: the form is displayed again 

The expected behavior is that the form should be hidden and display a message that you already have a loan for the literature instead.

**Comment by ntarocco** [comment]
closed by: https://github.com/inveniosoftware/react-invenio-app-ils/pull/244
