### ISSUE TITLE
Forms: problems with yup validation 

### ISSUE THREAD

**Issue by KonstantinaStoikou** [inveniosoftware/react-invenio-app-ils#243]
- [ ] error messages not displayed when input is invalid
  => only top-level errors are displayed because `yup` returns the errors in a different format than the server. Server returns a list of full path field names with an associated message, while `yup` returns an object of potentially other nested objects containing the errors in each field
  => error messages are not displayed for `SelectorField` components, because the error path does not match
- [x] some emails pass yup validation but get stop in marshmallow validation (e.g. emails with one letter after the dot such as something@something.c), this might also happen with urls because of different regex between marshmallow and yup
  => I would say it's not so much of an issue; domain name matching is already a complex topic. So long as both (backend + frontend) reject obvious non-email addresses, we are happy
- [x] in accordions the warning icon (that indicates that a field is invalid) is displayed as soon as you enter a row instead of when you submit the form
  => in `BaseForm`, disable both `validateOnChange` and `validateOnBlur`
- [x] date validation still happens in marshmallow (e.g. checks if start_date < end_date)
- [ ] authors in document form are validated in marshmallow
- [ ] some forms and fields (e.g. orders) need yup validation

**Comment by FlorianCassayre** [comment]
About the "flatness" inconsistency problem, I figured that we could intercept the http error responses with axios and serialize the data to have it nested. This implies that we also have to update all the form components aswell to gather errors from `_get(errors, fieldPath)` instead of the current `errors[fieldPath]`. Shouldn't be a huge task though.
