### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by janequist** [inveniosoftware/react-invenio-app-ils#257]
Started looking into this project for evaluation recently. It seems to have a good architecture, performant and well written code. 

There are some questions and a few issues I notice - so thought I'd file it as and when I get time, to get things going.

It seems that the UI for Pagination control grows indefinitely as the number of pages increase i.e it shows a page button for each page without limiting the width. So, the problem is two-fold
a. it cannot accommodate more than a dozen or so pages that can be fitted into the UI on the screen. b. it also makes for a broken UI navigation+presentation - cannot go to the pages past the 6th page in the screenshot - plz see attached. 

I am running the web version with local Docker on Mac using only the included demo data.

Thx/MJ.
<img width="893" alt="Screen Shot 2020-10-27 at 10 06 01 PM" src="https://user-images.githubusercontent.com/55568478/97397426-6dc1fe80-18a6-11eb-8d7d-c5159106a3b8.png">

**Comment by kprzerwa** [comment]
Thank you for the nice words and for reporting this issue.

I would like to mention that in general we didn't plan to have the backoffice responsive - so you might run into couple of issues on small resolutions. Can you tell us what's the resolution you've seen this bug appearing ?

We have made recently some fixes for the pagination component, which haven't been merged yet, so there are some improvements coming.

We will also complete the documentation for this project in the incoming months, I hope it will be useful for your evaluation. :)

**Comment by janequist** [comment]
The resolution is standard desktop/laptop (MacBookPro15" with and without external monitor). I haven't tried it on mobile.

**Comment by FlorianCassayre** [comment]
You raised a good point; while the backoffice is not meant to be responsive, it does not always behave well on smaller screens. Here is my attempt at reproducing it (~1220px wide):

![Capture d’écran de 2020-11-06 17-20-56](https://user-images.githubusercontent.com/9027075/98389667-a6a36580-2054-11eb-87cc-f427ec0de27b.png)

The pagination was made lighter (for a different reason). Moreover the number of displayed pages is limited: when there are more than 7 pages the components collapses and displays <kbd>...</kbd> instead. But clearly this is not enough to prevent overflow.
Perhaps we should make the sidebar collapsible to leave more space for the content. This should be discussed.

The application is still under heavy development and things may evolve rapidly. We are nevertheless always open to input and feedback.

**Comment by kprzerwa** [comment]
the pagination component is now fixed in v1.0.0-alpha.19 - for old laptop standard resolution (1366px, 1280px). @FlorianCassayre resolutions less than 1280px are rather deprecated (please see f.e. https://screensiz.es/monitor)
please reopen this issue in case of any further problems
