### ISSUE TITLE
search: history

### ISSUE THREAD

**Issue by FlorianCassayre** [inveniosoftware/react-invenio-app-ils#274]
### Reproduce

* visit to the [frontsite search page](https://127.0.0.1:3000/search)
* click on page 2
* from your browser, go back one page
* the search results reload and the url changes but the page still indicates 2 (should be 1)

It's a remaining problem from #196

**Edit**: It's a bug on `react-searchkit`.

**Comment by ntarocco** [comment]
yes, it is also happening if you select a filter, then go back. URL changes, but the state of the RSK is still the previous.

**Comment by FlorianCassayre** [comment]
That's where I tested it, the bug is still there.
