### ISSUE TITLE
Cancel option on edit pages - minor usability 

### ISSUE THREAD

**Issue by janequist** [inveniosoftware/react-invenio-app-ils#281]
## Is your feature request related to a problem? Please describe.
Backoffice - all edit pages (Document, Physical copies, Electronic items, etc.)
Select an item and go to Details page and Edit
No option to Cancel (only Submit)

## Describe the solution you'd like
Although Browser back button is a workaround, it is customary/standard practice to include Cancel button on such pages - the Librarian will be wondering if she/he did something wrong.

**Comment by FlorianCassayre** [comment]
:+1: for this feature

See #178

**Comment by FlorianCassayre** [comment]
Duplicates #178, closing this issue.
