### ISSUE TITLE
Electronic items filter check box - minor

### ISSUE THREAD

**Issue by janequist** [inveniosoftware/react-invenio-app-ils#282]
Package version (if known): <version> alpha.17

## Describe the bug
The filter selection check boxes on Electronic items page (Backoffice) do not check/select the box and provide visual feedback upon toggling.

## Steps to Reproduce
1. Go to Electronic Items search page
2. Click on one of the 'Open Access' filters
3. No visual change to the check box, although the filter is applied correctly.

## Additional context
Works properly in the other search pages.

**Comment by jrcastro2** [comment]
Thanks for your feedback!
This issue will be fixed in the next releases.
Fixed by https://github.com/inveniosoftware/react-searchkit/pull/155
