### ISSUE TITLE
frontsite: filters bug in mobile version

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/react-invenio-app-ils#287]
Package version (if known): v1.0.0-alpha.17

## Describe the bug
In the mobile version the filters are not working correctly if the length of the filters label is too long.

## Steps to Reproduce
1. Go to frontsite while displaying the web in a mobile device
2. Click on search
3. Try to filter by "Related content"
4. See the filters outside the screen

## Expected behavior
The filters section should not change the position depending on the labels length, it should be on the same position and shorten the labels length if they are too long.

### Correct display of filters
![image](https://user-images.githubusercontent.com/15194802/98529794-5e678b80-227e-11eb-944c-cb8b5d54658e.png)
### Bugged filters
![image](https://user-images.githubusercontent.com/15194802/98529835-6aebe400-227e-11eb-8b61-d76bd2970e57.png)

**Comment by FlorianCassayre** [comment]
See also #267
