### ISSUE TITLE
frontsite: literature searchbar shadow

### ISSUE THREAD

**Issue by FlorianCassayre** [inveniosoftware/react-invenio-app-ils#288]
A shadow hides behind the searchbar...
It's coming from: [`.ui.container.literature-search-container:after`](https://github.com/inveniosoftware/react-invenio-app-ils/blob/master/src/semantic-ui/site/elements/container.overrides#L198). I'm guessing the intended behavior is that the shadow should take the entire width. Or do we need a shadow at all?

![image](https://user-images.githubusercontent.com/9027075/98545676-1e140780-2296-11eb-8cab-d35f594b0522.png)

**Comment by kprzerwa** [comment]
the shadow is working as intended
