### ISSUE TITLE
Covers improvements

### ISSUE THREAD

**Issue by kprzerwa** [inveniosoftware/react-invenio-app-ils#296]
### Search page:
- provide one size for each cover. In case of the cover is smaller than the container fixed width and height, leave a white background around the cover, when it is bigger display with `background-size: cover` (or apply for all if the first variant too difficult)

### Cover styling (details page and search)
- apply a discrete, (but visible) border around the cover image, since some of the covers have white background and it is not possible to distinguish the edge of the image)

**Comment by FlorianCassayre** [comment]
Experimenting with `object-fit: contain`, `width: 100%` and `height: 200px`:
![image](https://user-images.githubusercontent.com/9027075/102509026-59200c80-4086-11eb-9e3e-08952597b428.png)
Additionally `background: none` because S-UI displays a gray background by default.
