### ISSUE TITLE
Sign out issue

### ISSUE THREAD

**Issue by janequist** [inveniosoftware/react-invenio-app-ils#316]
Upon signout, it throws the user to the invenio server that returns a 'Not found' page.

Instead it should return gracefully back to the Login page (Home page is acceptable, but not ideal because some libraries may prefer to not have open search access, but only within their communities)

Also plz ensure browser Back or Refresh, after logout, does not allow access to pages. The session management seems to work in general, but once or twice I encountered an error. In any case, needs to be tested (could get tricky if multiple tabs or windows are open).

**Comment by ntarocco** [comment]
Hi, it would be great if you more details about this.
Can you please describe how to reproduce it?

**Comment by janequist** [comment]
Hi,

When you "Sign out" either from the frontsite or backoffice, the screen I get is attached below. Obviously, doesn't make sense to be taken to invenio server 404 page and if you login here, it goes to the server admin page - instead should be taken back to the ILS login page upon logout. Hope it's clear.

<img width="951" alt="Screen Shot 2021-01-07 at 7 22 28 PM" src="https://user-images.githubusercontent.com/55568478/103976283-35069700-512b-11eb-870d-ba0410fe2139.png">

**Comment by anikachurilova** [comment]
#https://github.com/inveniosoftware/invenio-app-ils/pull/1159
