### ISSUE TITLE
literature request: automatically prefill more fields to document 

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/react-invenio-app-ils#352]
## Describe the bug
When librarian creates a document based on literature request some fields are pre-filled automatically. Add missing fields (journal title, volume, pages).

**Comment by ntarocco** [comment]
Fixed with https://github.com/inveniosoftware/react-invenio-app-ils/pull/366

**Comment by agentilb** [comment]
- When we fill the form, not all the fields are transposed in the document form afterwards: 
- [ ]  Pages should go in Publication information Page range
- [ ]  Publication year should go in Publication year
- [ ]  Publisher should go in Publisher
- [ ]  Standard number should go in Identifier Scheme Standard number
- [ ]  Edition should go to Edition

- [ ]  Can the Payment mode and  Budget code  be pushed to the Acquisition order when it is created?
