### ISSUE TITLE
most loaned: sorting issue

### ISSUE THREAD

**Issue by kprzerwa** [inveniosoftware/react-invenio-app-ils#355]
Package version (if known): v1.0.0-alpha.26

## Describe the bug
On the landing page, the section of `Most loaned books` is broken due to incorrect sorting (it does not show the most loaned books)

**Comment by ntarocco** [comment]
This is not happening on InvenioILS apparently but only on the CDS-ILS overlay and it might have been fixed [here](https://github.com/CERNDocumentServer/cds-ils/pull/338): the issue was that the `react-searchkit` package was not bumped to the latest version.

**Comment by ntarocco** [comment]
Fixed with https://github.com/CERNDocumentServer/cds-ils/pull/338
