### ISSUE TITLE
Change SortBy/SortOrder by Sort components (backoffice)

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/react-invenio-app-ils#38]
## Describe the bug

The current sorting does not allow to handle correctly the default sorting order on empty query.
What happens is that the list of results is sorted by default `Newest` `Asc`, so basically you see the oldest.

## Steps to Reproduce

1. Go to home page
2. Click on click on search
3. See the list of results and default sort options

## The current behavior

Show oldest first by default.

## The expected behavior

Show newest first by default.

- [ ] as a side task, check all search pages and ensure that the sort by/sort order that they are showing results in the right order.

**Comment by kprzerwa** [comment]
this is only for the backoffice, frontsite has it's own sorting orders
