### ISSUE TITLE
Data integrity issue

### ISSUE THREAD

**Issue by neilharrisbrown** [inveniosoftware/react-invenio-app-ils#399]
Package version (if known): Latest (29)

## Describe the bug
Started to look into the React SearchKit with this project as an example and found an issue where the updated values are not consistently reflected back in Search results.

## Steps to Reproduce
1. Using the demo data, perform a search under "Physical Items" on say "cryptography" - it gives 2 items both of which are "Not on Loan"
2. Again using demo data, go to Loans and with same search for "cryptography", go to Details screen of any Pending Loan request for one of the demo users. 
3. Checkout the copy - everything shows updated status - so far so good.
4. Now go back to the Search screen for "Physical Items" and again search for "cryptography" - it still shows the same 2 items with "Not on Loan" 
5. But go to Details screen for the "Physical Item" and it shows "On Loan" (as expected).

## Expected behavior
The search in Step 4 above should show 1 item on "Not on Loan" and 1 item on "On Loan"

## Screenshots (if applicable)
Attached

## Additional context
Wasn't sure if it is a problem with React Search Kit, DB, API/query issue or application problem such as caching. So I tried to narrow it down as follows: Restarted the app to flush all stale values, also restarted DB/Docker and Server, but still same inconsistency in Search result and Details result. 

Am attaching screen shots but it is not difficult to reproduce.

**Comment by neilharrisbrown** [comment]
<img width="742" alt="Items Search" src="https://user-images.githubusercontent.com/80505283/110903802-d8576200-82bc-11eb-8811-af59c35e225b.png">

**Comment by neilharrisbrown** [comment]
<img width="808" alt="Items Search Post" src="https://user-images.githubusercontent.com/80505283/110903942-13599580-82bd-11eb-956a-b99ac7d31c7e.png">

**Comment by neilharrisbrown** [comment]
<img width="808" alt="CheckedOut" src="https://user-images.githubusercontent.com/80505283/110904189-72b7a580-82bd-11eb-8a37-0d112d2957fb.png">

**Comment by neilharrisbrown** [comment]
After checkout - search


<img width="808" alt="Items Search Post" src="https://user-images.githubusercontent.com/80505283/110904566-05584480-82be-11eb-8b9b-6e790519fb1a.png">

**Comment by ntarocco** [comment]
HI! Thank you for reporting this issue and the other one.
We will have a look on Monday, but from a very quick reading of the issue, do you have `celery` running in a console?
Every time you perform an action, you will need to have celery pushing updated data to Elasticsearch.

**Comment by neilharrisbrown** [comment]
Indeed, that seems to do the trick.

Thanks for the quick response.
