### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by neilharrisbrown** [inveniosoftware/react-invenio-app-ils#406]
Package version (if known): 29

## Describe the bug
Navigating links goes to error page

## Steps to Reproduce
1. Click on any of the 10 links (in Loans HIstory) under Document or Physical copies in the screenshot
2. Goes to error page

**Comment by neilharrisbrown** [comment]
<img width="1126" alt="Err" src="https://user-images.githubusercontent.com/80505283/111075811-e963c700-84a6-11eb-8799-faeec54678a5.png">

**Comment by KonstantinaStoikou** [comment]
Thank you for reporting that. It will be fixed by this [PR](https://github.com/inveniosoftware/react-invenio-app-ils/pull/418).
