### ISSUE TITLE
Unable to docker-compose due to prettier issues

### ISSUE THREAD

**Issue by meetarun** [inveniosoftware/react-invenio-app-ils#468]
Package version (if known):  react-invenio-app-ils v1.0.0-alpha.51
https://github.com/inveniosoftware/react-invenio-app-ils/tree/v1.0.0-alpha.51

## Describe the bug

When you do docker-compose / npm start , the build continuously throws prettier error messages 

## Steps to Reproduce
1. Clone the code from https://github.com/inveniosoftware/invenio-app-ils
2. cd invenio-app-ils
3. run the command  _docker-compose -f docker-compose.full.yml up_
4. See error the error's

```

  > [react-build 6/6] RUN REACT_APP_INVENIO_UI_URL="https://127.0.0.1"  REACT_APP_INVENIO_REST_ENDPOINTS_BASE_URL="https://127.0.0.1/api"  REACT_APP_ENV_NAME="dev"  npm run build:
#18 0.765
#18 0.765 > @inveniosoftware/react-invenio-app-ils@1.0.0-alpha.51 build /code
#18 0.765 > craco build
#18 0.765
#18 2.995 Creating an optimized production build...
#18 139.9 Failed to compile.
#18 139.9
#18 139.9 ./src/lib/pages/backoffice/Document/DocumentEditor/schema.js
#18 139.9   Line 11:16:  Replace `'title',·'authors',·'publication_year',·'document_type',·'languages'` with `⏎······'title',⏎······'authors',⏎······'publication_year',⏎······'document_type',⏎······'languages',⏎····`  prettier/prettier
#18 139.9
#18 139.9 Search for the keywords to learn more about each error.
#18 139.9
#18 139.9
#18 140.5 npm ERR! code ELIFECYCLE
#18 140.5 npm ERR! errno 1
#18 140.5 npm ERR! @inveniosoftware/react-invenio-app-ils@1.0.0-alpha.51 build: `craco build`
#18 140.5 npm ERR! Exit status 1
#18 140.5 npm ERR!
#18 140.5 npm ERR! Failed at the @inveniosoftware/react-invenio-app-ils@1.0.0-alpha.51 build script.
#18 140.5 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#18 140.6
#18 140.6 npm ERR! A complete log of this run can be found in:
#18 140.6 npm ERR!     /root/.npm/_logs/2021-07-31T17_18_21_252Z-debug.log  

```

## Expected behavior
          Build should pass and  launch the app

<img width="1384" alt="Screenshot 2021-07-31 at 11 03 18 PM" src="https://user-images.githubusercontent.com/11626180/127748097-c27183b6-f81a-496d-a2e8-9c920e78c2c6.png">

## Additional context
        I found this Pull Request is the one which caused the issue..
https://github.com/inveniosoftware/react-invenio-app-ils/pull/464

FYI : @kprzerwa  @Pineirin

**Comment by kprzerwa** [comment]
hello @meetarun !
Thank you for pointing this out, the issue should be solved now in the latest version
