### ISSUE TITLE
filter visible on 0 results

### ISSUE THREAD

**Issue by kprzerwa** [inveniosoftware/react-invenio-app-ils#5]
<img width="3204" alt="Screenshot 2020-05-26 at 11 18 01" src="https://user-images.githubusercontent.com/38131488/82883472-bca7e880-9f42-11ea-9896-21e112deaf4a.png">

Only one filter remains visible when 0 results found, it should not be there

**Comment by FlorianCassayre** [comment]
The issue comes from the data returned by the endpoint: on an empty result the aggregation field `availability` has a non empty `bucket` (it should be empty). We could patch the frontend by filtering all the values whose count is zero but I think it's better to fix the backend API.
