### ISSUE TITLE
backoffice: PatronDetails: Clear search bar after checkout

### ISSUE THREAD

**Issue by sakshamarora1** [inveniosoftware/react-invenio-app-ils#616]
When doing the scanning, the loan is automatically created, but the barcode stays in the check out search bar.

**Comment by salomerohr** [comment]
Looks fine to me! I just got an error when I tried to issue the loan with first scanning the barcode and then selectin the user:


![Image](https://github.com/inveniosoftware/react-invenio-app-ils/assets/80258882/f5ee8c04-3357-4531-86c3-3a42cb6e8669)

**Comment by kpsherva** [comment]
> Looks fine to me! I just got an error when I tried to issue the loan with first scanning the barcode and then selectin the user. It said 'No user' are corresponding to my search:
> 
> ![Image](https://private-user-images.githubusercontent.com/80258882/331690393-f5ee8c04-3357-4531-86c3-3a42cb6e8669.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjc1NzcsIm5iZiI6MTcxNjM2NzI3NywicGF0aCI6Ii84MDI1ODg4Mi8zMzE2OTAzOTMtZjVlZThjMDQtMzM1Ny00NTMxLTg2YzMtM2E0MmNiNmU4NjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA4NDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYjBiOGU1MWRmMmU4ODNlZGM4MDFmN2M0MDcwMWU3OWNhZTM0NzQ4MWQ4Nzc1NDVjMDAwZTAyMjg2ZWVhN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Iz_KcLBAhIvQp3oqUQ3h_klwDrPSNgPZpnfLt-qqN4)

As you can see on the prompt above, the field requires either a patron ID (typed or provided by the scanner) or the full email (not the surname or first name)

**Comment by salomerohr** [comment]
Thanks for the info! So, there is a difference:
- from the document with 'Request loan for a patron', it works to search with the first or last name
- It does not work from the Item with 'Checkout this copy' (only email or ID)
Should it behave the same in both cases?

**Comment by salomerohr** [comment]
Works fine! Thanks a lot!
