### ISSUE TITLE
forms: MetadataExtensionsFields

### ISSUE THREAD

**Issue by topless** [inveniosoftware/react-invenio-app-ils#69]
We support extensions for two types of records: `documents` and `series`.
In order to edit these extensions fields we are using explicit component for each record type:

- `MetadataExtensions.js` for the document
- `SeriesMetadataExtensions.js` for the series

Create a common component `MetadataExtensionsFields.js` in `lib/forms/core`

**Comment by kprzerwa** [comment]
I would say to leave it as it is, since we might need two different ones in case we need them overridable
