### ISSUE TITLE
Checkout from item details page not working

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/react-invenio-app-ils#80]
Librarian registers a loan at the Library desk from the Physical copy page.

## Steps to reproduce

1. In backoffice, go to the item details page for an item that can circulate and it not on loan
2. click on "Checkout"
3. search for a user
4. Click on  "Checkout physical copy"

The loan is not created.

## Expected

The loan is created.

**Comment by FlorianCassayre** [comment]
Fixed by #118
