### ISSUE TITLE
bug: when authors missing frontsite series details page crash 

### ISSUE THREAD

**Issue by topless** [inveniosoftware/react-invenio-app-ils#87]
When we are trying to access series there is a stacktrace that should be handled about authors.

Find a series record from api `https://127.0.0.1:5000/api/series' and visit its details page on the front site `https://localhost:3000/literature/{series_pid}` you will see something like the following.

```
TypeError: Cannot read property 'slice' of undefined
DocumentAuthors.render

react-invenio-app-ils/dist/cjs/index.js:15095

  15092 | var displayedAuthors = authors;
  15093 | 
  15094 | if (!isExpanded) {
> 15095 |   displayedAuthors = authors.slice(0, limit);
        | ^  15096 | }
  15097 | 
  15098 | var isShowingAllAuthors = displayedAuthors.length === authors.length;
```

**Comment by kprzerwa** [comment]
hint: this was lately fixed for the document details page

**Comment by topless** [comment]
> hint: this was lately fixed for the document details page

Let me note to pay extra attention to `series` not just documents.

**Comment by jrcastro2** [comment]
Not able to reproduce it, currently if you visit the details page of a series (`https://localhost:3000/series/{series_pid}`) it works correctly
